version: '3.9'

services:
  ue1:
    container_name: ue1
    image: free5gc/ueransim:latest
    command: ./nr-ue -c ./config/ue1.yaml
    depends_on:
      - gnb1
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
    volumes:
      - ./config:/ueransim/config
    cap_add:
      - ALL
    devices:
      - "/dev/net/tun"
 
  ue2:
    container_name: ue2
    image: free5gc/ueransim:latest
    command: ./nr-ue -c ./config/ue2.yaml
    depends_on:
      - gnb1
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
    volumes:
      - ./config:/ueransim/configs
    cap_add:
      - ALL
    devices:
      - "/dev/net/tun"

