version: '3.9'

services:
  gnb1:
    container_name: gnb1
    image: free5gc/ueransim:latest
    command: ./nr-gnb -c ./config/gnb1.yaml
    ports:
      - "192.168.1.101:2152:2152" # Create unique network interface for each gnb
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
    volumes:
      - ./config:/ueransim/config
    cap_add:
      - ALL


